# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'techish'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'ddc9728c13474fc32447f109e8af6df03e2c8cd2'
    cliProjectName: 'JavaApp'
    cliSources: '.'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean install package'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/s/target/my-java-webapp.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'